# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy_db
spring.datasource.username=root
spring.datasource.password=tahiSifti1996@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring JDBC
spring.jdbc.template.query-timeout=30

# Show SQL in console
spring.jdbc.template.fetch-size=100

# Server Port
server.port=8081

# Disable Spring Security default password (we will configure manually)
spring.security.user.name=admin
spring.security.user.password=admin123